title: Wa Ode Sukmasarny Musdigaswati # your name (or website title) here
logo: "/images/logo-avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <img src="https://raw.githubusercontent.com/aemmadi/aemmadi/master/wave.gif" width="30px"> Welcome to my GitHub Page!
  <br><br>
  This is my portfolio on data science and machine learning. It contains some of my projects which I used to hone my knowledge and skills.
  
  <div class="social" style="cursor:pointer; background-color:#0077B5;" onclick="window.open('https://www.linkedin.com/in/sukma-sarny-934380111/', '_blank').focus();">
    <img src="https://img.shields.io/badge/linkedin-0077B5?style=for-the-badge&logo=linkedin&logoColor=white&link=https://www.linkedin.com/in/sukma-sarny-934380111/" alt="LinkedIn">
  </div>
  
  <div class="social" style="cursor:pointer; background-color:#121011;" onclick="window.open('https://github.com/sukmasarny', '_blank').focus();">
    <img src="https://img.shields.io/badge/github-121011?style=for-the-badge&logo=github&logoColor=white&link=https://github.com/sukmasarny" alt="GitHub">
  </div>

  
theme: jekyll-theme-minimal
# remote_theme: "godalming123/minimal"
